# Site settings
baseurl = "https://auryn31.github.io/homepage/"
languageCode = "en-us"
title = "Auryns Website"
theme = "freelancer"
publishDir = "docs"


[params]

    # You can use Markdown syntax for urls [text](//url.to/source) for
    # most longer texts.

    # To provide some metadata for search engines feel free to add a few
    # information about you and your website.
    name = "Aury Engel"
    description = "iOS Developer - Java Developer - Student"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email youself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    email = "auryn31@gmx.de"

    # Custom assets
	custom_css = []
	custom_js  = []

    [params.navigation]
        brand = "ENGEL"


    [params.header]
        # Copy your own image into './static/img/'' if you wish
        image = "profilbild.png"
        name = "Auryn Engel"
        subtitle = "iOS Developer - Java Developer - Student"


    [params.portfolio]
        # All projects defined in their own files. You can find example projects
        # at 'exampleSite/data/projects'. Copy the 'projects' folder into the 'data' directory
        # at the root of this Hugo site.
        # For more informtion take a look at the README.
        title = "Experience"

        [params.portfolio.modal]
            client = "Client"
            date = "Date"
            category = "Category"
            buttontext = "Close"


    [params.about]
        title = "About"
        left = "I am a student at the university Leipzig. My current goal is the graduation with a master of science in computer science. I graduated from the HTWK as one of 7 students. We started with about 70 students."
        right = "This is a work robe of mine, so they can get a picture of what my current status is and what they can expect from me. My tasks i do with best knowledge and certain and hope to be able to satisfy my customers."

        # [params.about.button]
        #     text = "Download theme"
        #     link = "//github.com/digitalcraftsman/hugo-freelancer-theme/archive/master.zip"
        #     icon = "download"

    [params.curriculum]
            title = "Curriculum Vitae"

    [params.contact]
        title = "Contact"

        # 'error' defines error messages for invalid inputs
        [params.contact.form.name]
            text = "Name"
            error = "Please enter your name."

        [params.contact.form.email]
            text = "Email Address"
            error = "Please enter your email address."

        [params.contact.form.phone]
            text = "Phone Number"
            error = "Please enter your phone number."

        [params.contact.form.message]
            text = "Message"
            error = "Please enter a message."

        [params.contact.form.button]
            text = "Send"


    [params.footer]
        copyright = "Published under the Apache License 2.0. Powered by [Hugo](//gohugo.io)."

        [params.footer.location]
            title = "Location"
            # Postal address (add as many lines as necessary)
            address = ["Augustusplatz 10", "04109 Leipzig"]

        [params.footer.social]
            title = "Around the web"
            # All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
            # for more icons. The icons are represented by their corresponding
            # CSS class.
            [[params.footer.social.networks]]
                icon = "fa-github"
                link = "//github.com/auryn31"

            [[params.footer.social.networks]]
                icon = "fa-stack-overflow"
                link=  "//stackoverflow.com/users/7927982/auryn31"

            [[params.footer.social.networks]]
                icon = "fa-facebook"
                link=  "//www.facebook.com/"

            [[params.footer.social.networks]]
                icon = "fa-xing"
                link=  "//www.xing.com/profile/"

        [params.footer.credits]
            title = "About Freelancer"
            text = "Freelance is a free to use, open source Bootstrap theme created by [Start Bootstrap](//startbootstrap.com). Icons by [DryIcons](//dryicons.com). Pictures from [mmtstock](http://mmtstock.com/collection/work-tech/)"
